package es.etg.dam.acceso;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class InstitutoOracleXeDAOImp implements InstitutoDAO {

    private Connection conn;
    private final String URL = "jdbc:oracle:thin:%s/%s@localhost:1521/XEPDB1";
    private final String DATABASE_USER = "usuario";
    private final String DATABASE_PASS = "usuario";

    public InstitutoOracleXeDAOImp() throws Exception {
        conn = DriverManager.getConnection(String.format(URL, DATABASE_USER, DATABASE_PASS));
    }

    @Override
    public void crearTabla() throws SQLException {

        String sqlCurso = "CREATE TABLE curso ("
                + "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "nombre VARCHAR2(100) NOT NULL, "
                + "descripcion VARCHAR2(200), "
                + "alumno_nombre VARCHAR2(50) NOT NULL, "
                + "CONSTRAINT fk_alumno FOREIGN KEY (alumno_nombre) REFERENCES alumno(nombre))";

        try (PreparedStatement ps1 = conn.prepareStatement(sqlCurso)) {
            ps1.executeUpdate();
        }
    }

    @Override
    public int insertarCurso(String nombreCurso, String descripcion, Alumno alumno) throws SQLException {
        String sql = "INSERT INTO curso (nombre, descripcion, alumno_nombre) VALUES (?, ?, ?)";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, nombreCurso);
            stmt.setString(2, descripcion);
            stmt.setString(3, alumno.getNombre());
            return stmt.executeUpdate();
        }
    }

    @Override
    public List<Alumno> listarAlumnos() throws SQLException {
        List<Alumno> alumnos = new ArrayList<>();
        String sql = "SELECT nombre, apellido, edad FROM alumno";

        try (PreparedStatement stmt = conn.prepareStatement(sql); ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                alumnos.add(new Alumno(
                        rs.getString("nombre"),
                        rs.getString("apellido"),
                        rs.getInt("edad")
                ));
            }
        }

        return alumnos;
    }

    @Override
    public int insertar(Alumno a) throws SQLException {
        String sql = "INSERT INTO alumno (nombre, apellido, edad) VALUES (?, ?, ?)";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, a.getNombre());
            stmt.setString(2, a.getApellido());
            stmt.setInt(3, a.getEdad());
            return stmt.executeUpdate();
        }
    }

    @Override
    public int actualizar(Alumno a) throws SQLException {
        String sql = "UPDATE alumno SET apellido = ?, edad = ? WHERE nombre = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, a.getApellido());
            stmt.setInt(2, a.getEdad());
            stmt.setString(3, a.getNombre());
            return stmt.executeUpdate();
        }
    }

    @Override
    public int borrar(Alumno a) throws SQLException {
        String sql = "DELETE FROM alumno WHERE nombre = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, a.getNombre());
            return stmt.executeUpdate();
        }
    }
    @Override
    public int actualizarCurso(int idCurso, String nuevoNombre, String nuevaDesc) throws SQLException {
        String sql = "UPDATE curso SET nombre = ?, descripcion = ? WHERE id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, nuevoNombre);
            stmt.setString(2, nuevaDesc);
            stmt.setInt(3, idCurso);
            return stmt.executeUpdate();
        }
    }

// LISTAR CURSOS CON ALUMNOS

    @Override
    public List<String> listarCursosConAlumnos() throws SQLException {
        String sql = "SELECT c.id, c.nombre, c.descripcion, a.nombre AS alumno "
                + "FROM curso c JOIN alumno a ON c.alumno_nombre = a.nombre";

        List<String> cursos = new ArrayList<>();
        try (PreparedStatement stmt = conn.prepareStatement(sql); ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                cursos.add("ID: " + rs.getInt("id")
                        + " | Curso: " + rs.getString("nombre")
                        + " | Desc: " + rs.getString("descripcion")
                        + " | Alumno: " + rs.getString("alumno"));
            }
        }
        return cursos;
    }

// LISTAR ALUMNOS POR EDAD
    @Override
    public List<Alumno> listarAlumnosPorEdad(int edadMin) throws SQLException {
        String sql = "SELECT nombre, apellido, edad FROM alumno WHERE edad >= ?";
        List<Alumno> alumnos = new ArrayList<>();

        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, edadMin);
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    alumnos.add(new Alumno(
                            rs.getString("nombre"),
                            rs.getString("apellido"),
                            rs.getInt("edad")));
                }
            }
        }
        return alumnos;
    }
}
